image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
environment:
  nodejs_version: "12"
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - cmd: choco install dotnetcore-sdk
  - dotnet --version
  - dotnet restore
  - choco install googlechrome
build_script:
- dotnet build
- npm -g install npm@latest
- cd src\AngularClientImplicitFlow
- npm install
- npm run build-production
- cd ..\ResourceWithIdentityServerWithClient
- npm install
- npm run build-production
before_build:
- appveyor-retry dotnet restore -v Minimal
